### ISSUE TITLE
Detect and work around DNS hijacking by ISPs

### ISSUE THREAD

**Issue by graphiclunarkid** [openrightsgroup/OrgProbe#1]
Some ISPs intercept DNS resolution failures and redirect to a serach page (https://en.wikipedia.org/wiki/DNS_hijacking#Manipulation_by_ISPs).

OrgProbe currently reports "OK" when checking non-existent domains if DNS hijacking is taking place. This is because it's only looking for a successful HTTP status code and page content being returned that does not include the strings found in the config file for the current ISP.

OrgProbe should detect that DNS hijacking is taking place and report "error" for non-existent domains. Ideally it would record that the error in question is "NXDOMAIN" so that we know the DNS resolution failed.

See openrightsgroup/cmp-issues#29 for further discussion.

**Comment by edjw** [comment]
As https://github.com/openrightsgroup/cmp-issues/issues/29 is closed, I guess this can be too
