### ISSUE TITLE
Enable varying timeouts for different transports

### ISSUE THREAD

**Issue by dantheta** [openrightsgroup/OrgProbe#3]
from https://github.com/openrightsgroup/cmp-issues/issues/60, we should allow a longer timeout for TLS sites, particularly those using longer key exchanges.

This should also work when the initial url is to an http:// site which redirects to https://.

**Comment by edjw** [comment]
I guess this can be closed as https://github.com/openrightsgroup/cmp-issues/issues/60 is closed
