### ISSUE TITLE
sslerror on a site using SNI and a Let's Encrypt X1 signed certificate

### ISSUE THREAD

**Issue by chriscroome** [openrightsgroup/OrgProbe#8]
Two ISPs, "BT-Light" and "VirginMedia" generate "   sslerror" results here:

https://www.blocked.org.uk/results?url=https://compassionate-revolution.net/

At the time the test was run the site was using a Let's Encrypt X1 signed cert, it now has a X3 signed one, see:

https://community.letsencrypt.org/t/upcoming-intermediate-changes/13106

I see there was an issue with SNI in the past:

https://github.com/openrightsgroup/OrgProbe/issues/5

Is this causing the problem? The TLS setup is all good according to SSL Labs (for modern browsers):

https://www.ssllabs.com/ssltest/analyze.html?d=compassionate-revolution.net

I have looked at the code but I'm afraid it didn't help me understand the cause of the issue:

https://github.com/openrightsgroup/OrgProbe/search?utf8=%E2%9C%93&q=sslerror

I'm raising this as the people behind the site are getting reports of people having problems accessing it, see this letter for the context:

http://www.theguardian.com/politics/2016/apr/18/use-tax-disobedience-to-create-a-fairer-society

**Comment by dantheta** [comment]
The fixed-line ISPs themselves don't deal with SSL very well in their
parental control web filtering system.  BT and Virgin both use a
DNS-based filter, which directs requests for targeted domains to their
proxy servers.  These proxy servers don't respond to HTTPS.  They used
to just refuse HTTPS connections but it now appears that they accept the
connection and terminate it.  Our probe software recognises this as an
SSL error and records that as the test result.

Looking at the non-HTTPS results for the compassionate-revolution site,
it appears to be blocked on BT and Virgin Media.

Hope that helps!

**Comment by chriscroome** [comment]
Could that be because HTTP requests are redirected to HTTPS rather than anything else? This is the Apache code the site uses:

```apache
<IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteCond %{HTTPS} !=on
  RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
</IfModule>

Header set Strict-Transport-Security "max-age=31536000" env=HTTPS
```

**Comment by dantheta** [comment]
I don't think so.  Here's the CURL output for retrieving http://compassionate-revolution.net over HTTP on the BT line:
```
# curl -v http://compassionate-revolution.net
* About to connect() to compassionate-revolution.net port 80 (#0)
*   Trying 213.120.234.154...
* connected
* Connected to compassionate-revolution.net (213.120.234.154) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.26.0
> Host: compassionate-revolution.net
> Accept: */*
> 
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 302 Found
< Connection: close
< Location: http://blockpage.bt.com/pcstaticpage/blocked.html?policy=Z2xvYmFsLWxpZ2h0LWQ2MzJjYmU0LTg1NWUtNDlhMC1iMTE3LTI1N2EyNmU1MDVhOA==;&view=ZDYzMmNiZTQtODU1ZS00OWEwLWIxMTctMjU3YTI2ZTUwNWE4;&list=BT-Light&originalUrl=aHR0cDovL2NvbXBhc3Npb25hdGUtcmV2b2x1dGlvbi5uZXQv
```

Note that the IP address retrieved for the site is not your regular IP; it's BT's proxy server.

**Comment by chriscroome** [comment]
This is another site on the same IP which doesn't have an issue:

https://www.blocked.org.uk/results?url=https://alt-sheff.org/

So could BT and Virgin proxy / porn filters have been triggered because the domain name contains the word "passion", com**passion**ate-revolution.net ?

**Comment by anadahz** [comment]
As @dantheta mentioned BT and Virgin are using [DNS hijacking](https://en.wikipedia.org/wiki/DNS_hijacking) to block/filter the domain names.

If I recall correctly they have a myriad of checks, keyword filtering is one of them.

**Comment by dantheta** [comment]
The substring "passion" is a possibility.  Some content scanners also watch out for mentions of drugs, weapons or violence in the page content itself.  If a domain name has been previously registered, a blocklist entry can relate to the previous usage of the domain name rather than the current one.  It can be hard to find out what caused a site to go onto the block lists.  Sky and TalkTalk provide obfuscated category information in the block page redirects which can give a hint, but BT and Virgin don't provide any information of this type.

**Comment by chriscroome** [comment]
So I guess what is needed to close this ticket is a more informative result output than "sslerror" and / or some changes to the [FAQ](https://www.blocked.org.uk/faq) to explain what this result means?

**Comment by edjw** [comment]
@dantheta – I think we can close this given we now put the "View the non-HTTPS results for this site." banner on https sites
